a_libs/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my/', include('backend.urls', namespace='my')),
    path('profile/', include('members.urls', namespace='profile')),
    path('download/<path>', serve, settings.MEDIA_ROOT),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
    path('', include('read.urls', namespace='read')),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/urls.py
from django.urls import path
from .views import *

app_name = 'my'

urlpatterns = [
    path('', redirect_check, name='redirect'),
    path('book/', BookListUploaded.as_view(), name='book-list'),
    path('book/check/', upload_check, name='book-check'),
    path('book/upload/', UploadBook.as_view(), name='upload-a-book'),
    path('book/<slug:link>/', BookDetail.as_view(), name='book-detail'),
    path('book/<slug:link>/update', UpdateBook.as_view(), name='book-update'),
    path('book/<slug:link>/delete/', BookDelete.as_view(), name='book-delete'),
]

members/urls.py
from django.urls import path
from .views import *

app_name = 'profile'

urlpatterns = [
    path('', ProfileHome.as_view(), name='home'),
    # path('', profile_home, name='home'),
    path('check/', profile_ck, name='cek-profile'),
    path('create/', CreateProfile.as_view(), name='create-profile'),
    path('<str:pk>/update/', UpdateProfile.as_view(), name='update-profile'),
]

read/urls.py
from django.urls import path
from .views import *

app_name = 'read'

urlpatterns = [
    path('', AllBooksList.as_view(), name='book'),
    path('book/', AllBookList.as_view(), name='book-list'),
    path('maps/', maps_view, name='maps'),
    # path('<str:cats>/', CategorySearch, name='category'),
    path('<slug:link>/', BookDetailView.as_view(), name='detail'),
    path('<slug:link>/comment/', AddComment.as_view(), name='add-comment'),
    path('<str:link>/likes/', like_view, name='book-like'),
    path('<str:link>/view', insert_to_history, name='book-history'),
    path('<str:link>/view/', PdfView.as_view(), name='book-view'),
]

members/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, related_name='profile')
    profile_image = models.ImageField(upload_to='profile/img/', null=True, blank=True)
    name = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=255, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.user) + ' as ' + self.name

members/forms.py
from django import forms
from .models import UserProfile


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('name', 'phone', 'profile_image')

members/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy as rl, reverse
from django.views.generic import *
from .forms import *
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from read.models import HistoryRecord
from backend.models import Book


def profile_ck(request):
    get_profile = UserProfile.objects.filter(user_id=int(request.user.id))
    if get_profile.exists():
        return HttpResponseRedirect(reverse('profile:home'))
    else:
        return HttpResponseRedirect(reverse('profile:create-profile'))


class ProfileHome(ListView):
    template_name = 'member/main.html'
    model = HistoryRecord
    context_object_name = 'history'
    ordering = ['-pk']
    paginate_by = 6

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileHome, self).get_context_data(*args, **kwargs)
        userprofile = UserProfile.objects.get(user_id=self.request.user.id)
        new_book = Book.objects.order_by('-pk')[:3]

        context['userprofile'] = userprofile
        context['new_book'] = new_book
        return context

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(ProfileHome, self).dispatch(request, *args, **kwargs)


@login_required(login_url='/accounts/login/')
def profile_home(request):
    userprofile_ = UserProfile.objects.filter(user_id=request.user.id)
    if userprofile_.exists():
        userprofile = UserProfile.objects.get(user_id=request.user)
    else:
        return HttpResponseRedirect(reverse('profile:create-profile'))

    history = HistoryRecord.objects.filter(user_id=request.user.id)
    history = history.order_by('-pk')

    context = {
        'userprofile': userprofile,
        'user_': request.user,
        'history': history,
    }
    return render(request, 'member/main.html', context)


class CreateProfile(CreateView):
    model = UserProfile
    template_name = 'member/create.html'
    form_class = CreateProfileForm
    success_url = rl('profile:home')

    def form_valid(self, form):
        form.instance.user_id = self.request.user.id
        a = super(CreateProfile, self).form_valid(form)
        b = HttpResponseRedirect(self.get_success_url())
        return a and b

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        get_profile = UserProfile.objects.filter(user_id=self.request.user)
        if get_profile.exists():
            return redirect('profile:home')
        else:
            return super(CreateProfile, self).dispatch(request, *args, **kwargs)

    def get_template_names(self):
        return self.template_name


class UpdateProfile(UpdateView):
    model = UserProfile
    template_name = 'member/update.html'
    form_class = CreateProfileForm
    success_url = rl('profile:home')

    def form_valid(self, form):
        form.instance.profile_image = self.request.POST.get('profile_image')
        a = super(UpdateProfile, self).form_valid(form)
        b = HttpResponseRedirect(redirect(self.get_success_url()))
        return a, b

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(UpdateProfile, self).dispatch(request, *args, **kwargs)

members/templates/member/create.html
{% extends 'base.html' %}

{% block title %}Main Menu{% endblock %}

{% block content %}
    <section>
        <div class="jumbotron bg-primary">
            <div class="d-flex justify-content-center">
                <img src="assets/images/profile.svg" height="400" class="img-fluid jumbtrn-image" alt="">
            </div>
            <div class="container mt-5">
                <h1 class="text-center font-weight-bold">Edit Profile</h1>
                <p class="text-center text-white">{{ userprofile.name }}</p>
            </div>
        </div>
        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="profile">
                            <div class="card border-0">
                                <div class="card-body ">
                                    <div class="d-flex justify-content-center">
                                        <img src="assets/images/foto-profile.svg" height="150" alt="" class="foto-profile mt-5">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="card">
                            <div class="card-body">
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% load crispy_forms_tags %}
                                    {{ form.media }}
                                    {{ form | crispy }}
                                    <div class="form-group">
                                        <button class="btn btn-primary">Save</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

{% endblock %}

members/templates/member/main.html
{% extends 'base.html' %}

{% load static %}
{% load l10n %}
{% load i18n %}

{% block title %}Main Menu{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}

    <div class="jumbotron bg-primary">
        <div class="d-flex justify-content-center">
            <img src="{% static 'images/profile.svg' %}" height="400" class="img-fluid jumbtrn-image" alt="">

        </div>
        <div class="container mt-5">
            <h1 class="text-center font-weight-bold">PROFILE PAGE</h1>
        </div>
    </div>
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="profile">
                        <div class="card border-0">
                            <div class="card-body ">
                                <div class="d-flex justify-content-center">
                                    {% if not userprofile.profile_image  %}
                                    <img src="{% static 'images/foto-profile.svg' %}" height="150" alt="" class="foto-profile mt-5">
                                    {% else %}
                                    <img src="{{ userprofile.profile_image.url }}" height="150" alt="" class="foto-profile mt-5">
                                    {% endif %}

                                </div>

                                <h4 class="mt-4 mb-4">{{ userprofile.name }}</h4>
                                <hr>
                                <p>+62 {{ userprofile.phone }}</p>
                                <hr>
                                <div class="edit mb-5">
                                    <div class="d-flex flex-column ">
                                        <form action="{% url 'profile:update-profile' userprofile.pk  %}">
                                            <button class="btn btn-primary btn-lg">Update Data</button>
                                        </form>
                                        <form action="{% url 'my:upload-a-book' %}" class="mt-3">
                                            <button class="btn btn-lg btn-primary">Upload A Book Now</button>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>


                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="overview">
                        <h3 class="font-weight-bold ">Buku yang sedang dibaca</h3>
                        <p class="text-muted sub">Buku yang pernah dan sedang kamu baca : 6</p>
                        <div class="row">
                        {% for book in history %}
                            <div class="col-lg-4">
                                <div class="card mt-5 border-0">
                                    <div class="card-body">
                                        <img src="{{ book.book.cover.url }}" class="book-card img-fluid" alt="">
                                        <p class="font-weight-bold mt-3">{{ book.book.title }} </p>
                                        <p class="font-weight-lighter mt-2">at {{ book.time | date:"M d, Y - H:i" }} </p>
                                        <a href="/{{ book.book.get_absolute_url }}" class="text-primary text-decoration-none stretched-link">Baca Lagi</a>

                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                        </div>
                    </div>
                    {% if is_paginated %}=
                        <nav class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
                            <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Next"><span aria-hidden="true">« Previous</span></a></li>
                            {% endif %}
                                <li class="page-item active"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                            {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">Next »</span></a></li>
                            {% endif %}

                            </ul>
                        </nav>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>

    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#0275d8" fill-opacity="1" d="M0,224L48,197.3C96,171,192,117,288,112C384,107,480,149,576,176C672,203,768,213,864,202.7C960,192,1056,160,1152,128C1248,96,1344,64,1392,48L1440,32L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path></svg>
    <div id="suka" class="pb-5 pt-5">

        <div class="container">
            <h3 class="font-weight-bold text-white pt-5">Buku yang mungkin kamu suka</h3>
            <p class="mb-5 mt-3 text-white">Ini rekomendasi kami untuk kamu, mungkin aja <br> kamu suka dengan buku yang <br> kami rekomendasikan ini</p>
            <div class="row">
                {% for latest in new_book %}
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex justify-content-center">
                                                            <img src="{{ latest.cover.url }}" class="book-card img-fluid" alt="">

                            </div>
                            <p class="font-weight-bold mt-3">{{ latest.title }}</p>
                            <a href="" class="text-primary stretched-link">Lihat Buku</a>
                        </div>
                    </div>
                </div>
                {% endfor %}


            </div>
        </div>

    </div>

{% endblock %}

members/templates/member/update.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}Update Profile{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/profile-update.css' %}">
{% endblock %}

{% block content %}

    <section class=" mb-5">
        <div class="jumbotron bg-primary">
            <div class="d-flex justify-content-center">
                <img src="{% static 'images/profile.svg' %}" height="400" class="img-fluid jumbtrn-image" alt="">
            </div>
            <div class="container mt-5">
                <h1 class="text-center font-weight-bold">Edit Profile</h1>
                <p class="text-center text-white">{{ userprofile.name }}</p>
            </div>
        </div>
        <div class="content">
            <div class="container">
                <div class="row">

                    <div class="col-lg-12 mx-auto">
                        <div class="card">
                            <div class="card-body">
                                <form enctype="multipart/form-data" method="post">
                                    {% csrf_token %}
                                    {% load crispy_forms_tags %}
                                    {{ form | crispy}}
                                    <button type="submit" class="btn btn-primary">Simpan</button>
                                    <a href="{% url 'profile:home' %}" class="btn btn-danger">Cancel</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

{% endblock %}