a_libs/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my/', include('backend.urls', namespace='my')),
    path('profile/', include('members.urls', namespace='profile')),
    path('download/<path>', serve, settings.MEDIA_ROOT),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
    path('', include('read.urls', namespace='read')),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/urls.py
from django.urls import path
from .views import *

app_name = 'my'

urlpatterns = [
    path('', redirect_check, name='redirect'),
    path('book/', BookListUploaded.as_view(), name='book-list'),
    path('book/check/', upload_check, name='book-check'),
    path('book/upload/', UploadBook.as_view(), name='upload-a-book'),
    path('book/<slug:link>/', BookDetail.as_view(), name='book-detail'),
    path('book/<slug:link>/update', UpdateBook.as_view(), name='book-update'),
    path('book/<slug:link>/delete/', BookDelete.as_view(), name='book-delete'),
]

read/urls.py
from django.urls import path
from .views import *

app_name = 'read'

urlpatterns = [
    path('', AllBooksList.as_view(), name='book'),
    path('book/', AllBookList.as_view(), name='book-list'),
    path('maps/', maps_view, name='maps'),
    # path('<str:cats>/', CategorySearch, name='category'),
    path('<slug:link>/', BookDetailView.as_view(), name='detail'),
    path('<slug:link>/comment/', AddComment.as_view(), name='add-comment'),
    path('<str:link>/likes/', like_view, name='book-like'),
    path('<str:link>/view', insert_to_history, name='book-history'),
    path('<str:link>/view/', PdfView.as_view(), name='book-view'),
]

backend/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField
from django_ckeditor_5.fields import CKEditor5Field


class Category(models.Model):
    name = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255)
    link = models.SlugField(max_length=255, unique=True, default='') # ng usah
    book = models.FileField(upload_to='book/pdf/') # ng usah
    cover = models.ImageField(upload_to='book/cover/')
    author = models.CharField(max_length=255)
    availability = models.IntegerField(default=0)
    description = CKEditor5Field(null=True, blank=True, config_name='special')
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    pending = models.BooleanField(default=True) # ng usah
    upload_date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    category = models.ManyToManyField(Category, blank=True)

    def ttl_like(self):
        return self.likes.count()

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.book.delete()
        self.cover.delete()
        super().delete(*args, **kwargs)

    def get_absolute_url(self):
        return self.link

backend/forms.py
from django import forms
from .models import Book, Category

category_choices = Category.objects.all().values_list("id", "name")

category_list = []

for category in category_choices:
    category_list.append(category)


class UploadBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'book', 'cover', 'author', 'availability', 'description', 'category')

        widgets = {
            'category': forms.CheckboxSelectMultiple(choices=category_list)
        }


class UpdateUploadedBook(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'availability', 'description', 'category')

        widgets = {
            'category': forms.CheckboxSelectMultiple(choices=category_list)
        }

backend/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import *
from .models import Book
from .forms import UploadBookForm, UpdateUploadedBook
from django.db.models import Q as __
import os
from django.conf import settings
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from members.models import UserProfile
from .utils import staff_required

link = 'link'


@login_required(login_url="/accounts/login/")
def upload_check(request):
    profile_ = UserProfile.objects.filter(user_id=request.user.id)
    # print(profile_)
    if not profile_:
        # if user had create their profile
        return redirect('profile:create-profile')
    else:
        # if not create
        return redirect('my:upload-a-book')


def redirect_check(request):
    book = Book.objects.filter(uploader_id=request.user.id).count()
    if book != 0:
        return redirect('my:book-list')
    else:
        return redirect('my:book-check')


class BookListUploaded(ListView):
    model = Book
    template_name = 'backend/book-list.html'
    paginate_by = 10
    ordering = ['-id']

    def get_queryset(self):
        qq = self.request.GET.get('q')
        book_total = Book.objects.filter(uploader=self.request.user.id).count()

        if book_total != 0:
            if qq is not None:
                object_list = Book.objects.filter(
                    __(title__icontains=qq) | __(author__icontains=qq) |
                    __(description__icontains=qq) | __(link__icontains=qq)
                )
                object_list.filter(uploader=self.request.user.id)
            else:
                object_list = Book.objects.filter(uploader=self.request.user.id)
        else:
            return HttpResponseRedirect(reverse('my:book-check'))

        return object_list

    @method_decorator(login_required(login_url="/accounts/login/"))
    def dispatch(self, request, *args, **kwargs):
        return super(BookListUploaded, self).dispatch(request, *args, **kwargs)


class BookDetail(DetailView):
    model = Book
    template_name = 'backend/book-detail.html'
    query_pk_and_slug = True
    slug_field = link
    slug_url_kwarg = link

    def get_context_data(self, *args, **kwargs):
        context = super(BookDetail, self).get_context_data(*args, **kwargs)

        return context

    @method_decorator(login_required(login_url="/accounts/login/"))
    def dispatch(self, request, *args, **kwargs):
        return super(BookDetail, self).dispatch(request, *args, **kwargs)


@login_required(login_url="/accounts/login/")
def download(req, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type='application/file')
            response['Content-Dispotition'] = 'inline;filenam=' + os.path.basename(file_path)
            return response
    raise Http404


class UploadBook(CreateView):
    model = Book
    form_class = UploadBookForm
    template_name = 'backend/upload.html'
    success_url = reverse_lazy('my:book-list')

    def form_valid(self, form):
        form.instance.uploader_id = self.request.user.id
        link_ = str(self.request.POST.get('title'))
        str_id = str(self.request.user.id)
        link_ = str_id + '_' + link_
        link_ = link_.replace(" ", "-")
        form.instance.link = link_

        return super(UploadBook, self).form_valid(form) and HttpResponseRedirect(self.get_success_url())

    @method_decorator(login_required(login_url="/accounts/login/"))
    def dispatch(self, request, *args, **kwargs):
        return super(UploadBook, self).dispatch(request, *args, **kwargs)


class UpdateBook(UpdateView):
    model = Book
    form_class = UpdateUploadedBook
    template_name = 'backend/update.html'
    query_pk_and_slug = True
    slug_field = link
    slug_url_kwarg = link

    def get_success_url(self):
        return reverse('my:book-detail', args=[str(self.kwargs['link'])])

    def form_valid(self, form):
        a = super().form_valid(form)
        return a

    @method_decorator(login_required(login_url="/accounts/login/"))
    def dispatch(self, request, *args, **kwargs):
        return super(UpdateBook, self).dispatch(request, *args, **kwargs)


class BookDelete(DeleteView):
    model = Book
    template_name = 'backend/delete.html'
    query_pk_and_slug = True
    slug_field = link
    slug_url_kwarg = link
    success_url = reverse_lazy('my:book-list')

    def get_success_url(self):
        return self.success_url.format(**self.object.__dict__)

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(BookDelete, self).dispatch(request, *args, **kwargs)

backend/templates/backend/book-detail.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}
{{book.title}} | My
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'my/css/book-details.css' %}">
{% endblock %}

{% block content %}
        <section class="mb-5">
            <div class="book">
                <div class="container">
                    <h2 class="w-100 text-center my-4 book-title p-2">{{ book.title }}</h2>
                    <div class="row h-100 container1 mb-5">
                        <div class="col-md-5 col-sm-12 d-flex align-items-center">
                            <img src="{{ book.cover.url }}" alt="book-image" class="w-100 h-100 img-fluid">
                        </div>
                        <div class="col-md-7 col-sm-12 pt-md-0 pt-4 book-detail d-flex flex-column justify-content-around">
                            <div class="text-justify d-block h-75">

                                <div>
                                    <h4>Description</h4>
                                    <div>{{ book.description | safe }}</div>
                                </div>
                                <div class="mt-2">
                                    <h4>Category</h4>
                                    <p> {% for cat in book.category.all %} {{ cat }}, {% endfor %}</p>
                                </div>
                                <div class="mt-2">
                                    <h4>Uploader</h4>
                                    <p>{{ book.uploader.profile.name }}</p>
                                </div>
                                <div class="mt-2">
                                    <h4>Author</h4>
                                    <p>{{ book.author }}</p>
                                </div>
                                <div class="mt-2">
                                    <h4>Date</h4>
                                    <p>{{ book.upload_date | date:"M, d Y, H:i" }}</p>
                                </div>
                                <div class="mt-2">
                                    <h4>Likes</h4>
                                    <p>{{ book.ttl_like }}</p>
                                </div>
                            </div>

                            <div class="d-flex flex-column justify-content-between w-100 h-25">
                                <div class="d-flex flex-column w-100">
                                    <a href="{% url 'my:book-update' book.get_absolute_url %}" class="btn btn-primary rounded-pill mt-2">Update Book Data</a>
                                    <a download="{{ book.book.url }}" href="{{ book.book.url }}" class="btn btn-outline-primary rounded-pill mt-2">Download</a>
                                </div>
                                <form action="{% url 'my:book-delete' book.get_absolute_url %}" class="d-flex flex-column w-100">
                                    <button class="btn btn-outline-danger rounded-pill mt-2">Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}

backend/templates/backend/book-list.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}My Uploaded Books | My{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'my/css/uploaded-books.css' %}">
{% endblock %}

{% block content %}
<div class="jumbotron bg-primary">
    <div class="d-flex justify-content-center">
        <img src="{% static 'images/uploaded.svg' %}" height="400" class="img-fluid jumbtrn-image" alt="">

    </div>

    <div class="container mt-5">
        <h1 class="text-center font-weight-bold">My Uploaded Books</h1>
        <div class="d-flex justify-content-center">
            <a href="{% url 'my:upload-a-book' %}" class="btn btn-info">Unggah buku</a>

        </div>
    </div>
</div>

<div class="book">
    <div class="container">
        <div class="card mb-5">
            <div class="card-body">
                <form method="get" class="input-group ">
                    <input type="text" name="q" class="form-control" placeholder="Cari buku">
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
            </div>
        </div>


        <div class="row">
<!--            <div class="col-lg-12">-->
<!--                <div class="row mt-5">-->
                    {% for book in object_list %}
                    <div class="col-lg-4 my-4">
                        <a href="{% url 'my:book-detail' book.get_absolute_url %}">
                            <div class="card border-0 book-item">
                                <img src="{{ book.cover.url }}" alt="" class="card-img-top img-fluid">
                            </div>
                        </a>
                        <h4 class="mt-2">{{ book.title }}</h4>
                    </div>
                    {% endfor %}

                    {% if is_paginated %}
                    <nav class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Next"><span aria-hidden="true">«</span></a></li>
                            {% endif %}
                            <li class="page-item active"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                            {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                            {% endif %}

                        </ul>
                    </nav>
                    {% endif %}

<!--                </div>-->
<!--            </div>-->
        </div>
    </div>
</div>

{% endblock %}

backend/templates/backend/delete.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}Upload Book | My{% endblock %}

{% block style %}
<style>
    body {
    background-color: #eee;
    }
</style>
{% endblock %}

{% block content %}
<section class="my-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10 col-md-12">
                <div class="card mb-4">
                    <div class="card-body">
                        <h2>Delete Book</h2>
                        <h4>Book : {{ book.title }}</h4>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% load crispy_forms_tags %}
                            {{ form.media }}
                            {{ form | crispy }}
                            <button type="submit" class="btn btn-danger"> Delete </button>
                            <br>
                            <a href="{% url 'my:book-detail' book.get_absolute_url %}" class="mt-2 btn btn-outline-success rounded-pill"> Cancel </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}
{% endblock %}

backend/templates/backend/update.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}Update Book | My{% endblock %}

{% block style %}
<style>
    body {
    background-color : #eee;
    }
    .navbar {
        background-color: white;
    }
    .form-title{
        border-bottom: 1px solid lightgray;
    }
</style>
{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10 col-md-12">
                <div class="card mb-4">
                    <div class="card-body">
                        <h2>Upload book</h2>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% load crispy_forms_tags %}
                            {{ form.media }}
                            {{ form | crispy }}
                            <button type="submit" class="btn btn-primary"> Save </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}
{% endblock %}

backend/templates/backend/upload.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}Upload Book | My{% endblock %}

{% block style %}
<style>
    body {
    background-color : #eee;
    }
    .navbar {
        background-color: white;
    }
    .form-title{
        border-bottom: 1px solid lightgray;
    }
</style>
{% endblock %}

{% block content %}
<section class="my-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10 col-md-12">
                <div class="card mb-4">
                    <div class="card-body">
                        <h2>Upload book</h2>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% load crispy_forms_tags %}
                            {{ form.media }}
                            {{ form | crispy }}
                            <button type="submit" class="btn btn-primary"> Save </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}
{% endblock %}