a_libs/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my/', include('backend.urls', namespace='my')),
    path('profile/', include('members.urls', namespace='profile')),
    path('download/<path>', serve, settings.MEDIA_ROOT),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
    path('', include('read.urls', namespace='read')),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

read/urls.py
from django.urls import path
from .views import *

app_name = 'read'

urlpatterns = [
    path('', AllBooksList.as_view(), name='book'),
    path('book/', AllBookList.as_view(), name='book-list'),
    path('maps/', maps_view, name='maps'),
    # path('<str:cats>/', CategorySearch, name='category'),
    path('<slug:link>/', BookDetailView.as_view(), name='detail'),
    path('<slug:link>/comment/', AddComment.as_view(), name='add-comment'),
    path('<str:link>/likes/', like_view, name='book-like'),
    path('<str:link>/view', insert_to_history, name='book-history'),
    path('<str:link>/view/', PdfView.as_view(), name='book-view'),
]

templates/base.html
<!doctype html>
<html lang="en">

{% load static %}
{% load i18n %}
{% load l10n %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>{% block title %}{% endblock %} - BacaBuku</title>
    {% block style %}
    {% endblock %}
</head>

<body>
    <section>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="/">Baca Buku</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
                    <div class="navbar-nav ml-auto">
                        <a class="nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
                        <a class="nav-link" href="{% url 'read:book-list' %}">List Buku</a>
                        <a class="nav-link" href="/my/">Unggah Buku</a>
                        <a class="nav-link  " href="{% url 'read:maps' %}">Peta Perpustakaan</a>

                        {% if user.is_authenticated %}
                        <a class="nav-link text-danger font-weight-bold" href="{% url 'account_logout' %}">Logout</a>
                        {% else %}
                        <a class="nav-link font-weight-bold text-info" href="{% url 'account_login' %}">Login</a>
                        <a class="nav-link font-weight-bold text-success" href="{% url 'account_signup' %}">Register</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </nav>
    </section>

    {% block content %}
    {% endblock %}
    <footer>
        <div class="card">
            <div class="car-body">
                <div id="footer" class=" pt-5 pb-5">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-3 mt-4">
                                <h3>BACA <span class="text-primary">BUKU</span> </h3>
                                <p>Belajar apapun disini melalui buku yang sudah tersedia diwebsite ini.</p>
                                <div class="d-flex">
                                    <a href="https://www.instagram.com/smktelkomjakarta/"></a>
                                    <a href="https://www.facebook.com/smktelkomjkt"></a>
                                </div>
                            </div>
                            <div class="col-lg-3 mt-4">
                                <h4>Link Cepat</h4>
                                <div class="d-flex flex-column ">
                                    <a href="" class="text-primary">List buku</a>
                                    <a href="" class="text-primary">Register</a>
                                    <a href="" class="text-primary">Login</a>
                                </div>

                            </div>
                            <div class="col-lg-3 mt-4">
                                <h4> Resource</h4>
                                <div class="d-flex flex-column">
                                    <a href="">Unsplash</a>
                                    <a href="">Freepik</a>
                                    <a href="">Smk Telkom Jakarta</a>

                                </div>
                            </div>
                            <div class="col-lg-3 mt-4">
                                <h4>Lokasi</h4>
                                <a href="https://www.google.com/maps/place/SMK+Telkom+Jakarta/@-6.1544783,106.7485692,17z/data=!3m1!4b1!4m5!3m4!1s0x2e69f7c113c644b5:0xa3a809c8c4627262!8m2!3d-6.1544783!4d106.7507579?hl=id"><img src="{% static 'images/lokasi.jpg' %}" class="img-fluid"></a>
                            </div>
                        </div>

                    </div>

                </div>
                <div id="footer2" class="bg-primary text-center text-white pt-3 pb-3">
                    Created at @TIM P4
                </div>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/3.1.0/parallax.min.js"></script>
    {% block js %}
    {% endblock %}

</body>

</html>