a_libs/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my/', include('backend.urls', namespace='my')),
    path('profile/', include('members.urls', namespace='profile')),
    path('download/<path>', serve, settings.MEDIA_ROOT),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
    path('', include('read.urls', namespace='read')),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

read/urls.py
from django.urls import path
from .views import *

app_name = 'read'

urlpatterns = [
    path('', AllBooksList.as_view(), name='book'),
    path('book/', AllBookList.as_view(), name='book-list'),
    path('maps/', maps_view, name='maps'),
    # path('<str:cats>/', CategorySearch, name='category'),
    path('<slug:link>/', BookDetailView.as_view(), name='detail'),
    path('<slug:link>/comment/', AddComment.as_view(), name='add-comment'),
    path('<str:link>/likes/', like_view, name='book-like'),
    path('<str:link>/view', insert_to_history, name='book-history'),
    path('<str:link>/view/', PdfView.as_view(), name='book-view'),
]

read/models.py
from django.db import models
from ckeditor.fields import RichTextField
from backend.models import Book
from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field


class Comment(models.Model):
    book = models.ForeignKey(Book, related_name='comment', on_delete=models.CASCADE)
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    body = CKEditor5Field('Text', null=True, blank=True, config_name='special')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.book.title, self.name)


class HistoryRecord(models.Model):
    user = models.ForeignKey(User, related_name='user_history', on_delete=models.CASCADE)
    book = models.ForeignKey(Book, related_name='booking', on_delete=models.CASCADE)
    url = models.TextField(max_length=255)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + " membaca " + str(self.book)

read/forms.py
from django import forms
from .models import *


class AddCommentForms(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', )

read/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import *
from backend.models import Book, Category
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse, Http404, FileResponse
from django.urls import reverse, reverse_lazy
from .forms import *
from django.db.models import Count, Q
from members.models import UserProfile
from easy_pdf.views import PDFTemplateView, PDFTemplateResponseMixin
from django.core.files.storage import FileSystemStorage
from django.views.decorators.clickjacking import xframe_options_sameorigin


class AllBooksList(TemplateView):
    template_name = 'read/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super(AllBooksList, self).get_context_data(*args, **kwargs)
        fav_book = Book.objects.all().order_by('likes')[:6]
        book_total = Book.objects.all().count()
        member = User.objects.all().count()
        category = Category.objects.all().count()

        context['fav_books'] = fav_book
        context['book_total'] = book_total
        context['member'] = member
        context['category'] = category
        return context


# def like_view(request, pk):
#     book = get_object_or_404(Book, id=request.POST.get('book_id'))
#     current_score = book.current_rate()
#     rated = False
#     # Delete rating the book
#     if book.user_rating.filter(id=request.user.id).exists():
#         pass
#     else:
#         book.user_rating.add(request.user)
#         current_score += int(request.POST.get('rating_point'))
#         rated = True
#
#     return HttpResponseRedirect(reverse('book-detail', args=[str(pk)]))


class BookDetailView(DetailView):
    template_name = 'read/details.html'
    # template_name = 'read/base1.html'
    query_pk_and_slug = True
    slug_url_kwarg = 'link'
    slug_field = 'link'
    model = Book

    def get_context_data(self, *args, **kwargs):
        context = super(BookDetailView, self).get_context_data(*args, **kwargs)
        category = Category.objects.all()
        tile = Book.objects.get(link=self.kwargs['link'])
        profile_ = UserProfile.objects.filter(user_id=Book.objects.get(pk=tile.pk).uploader)
        if profile_ is not None:
            profile = UserProfile.objects.get(user_id=Book.objects.get(pk=tile.pk).uploader)
            context['profile'] = profile
        else:
            pass
        stuff = get_object_or_404(Book, link=self.kwargs['link'])
        liked = False
        if stuff.likes.filter(id=self.request.user.id).exists():
            liked = True

        context['category'] = category
        context['liked'] = liked
        return context


class AddComment(CreateView):
    model = Comment
    form_class = AddCommentForms
    template_name = 'read/add-comment.html'
    query_pk_and_slug = True
    slug_field = 'link'
    slug_url_kwarg = 'link'

    def get_success_url(self):
        return reverse('read:detail', args=[str(self.kwargs['link'])])

    def form_valid(self, form):
        pk = Book.objects.get(link=self.kwargs['link'])
        form.instance.book_id = pk.pk
        form.instance.name_id = self.request.user.id
        return super().form_valid(form) and HttpResponseRedirect(self.get_success_url())

    @method_decorator(login_required(login_url="/accounts/login/"))
    def dispatch(self, request, *args, **kwargs):
        return super(AddComment, self).dispatch(request, *args, **kwargs)


# def CategorySearch(req, cats):
#     cate = Book.objects.filter(category=cats.replace('-', ' '))
#     con = {
#         'cats': cats.replace('-', ' ').title(),
#         'category_posts': cate
#     }
#     return render(req, '', con)


class AllBookList(ListView):
    model = Book
    template_name = 'read/list.html'
    paginate_by = 6
    ordering = ['-pk']

    def get_queryset(self):
        qq = self.request.GET.get('q')
        if qq is not None:
            object_list = Book.objects.filter(
                Q(title__icontains=qq) | Q(link__icontains=qq) | Q(description__icontains=qq)
            ).order_by('-pk')
        else:
            object_list = Book.objects.all().order_by('-pk')

        return object_list

    def get_context_data(self, *args, **kwargs):
        context = super(AllBookList, self).get_context_data(*args, **kwargs)
        fav_book = Book.objects.all().order_by('likes')[:4]
        new_book = Book.objects.all().order_by('-pk')[:1]
        cat = Category.objects.all().order_by('-pk')[:3]

        context['category'] = cat
        context['new_book'] = new_book
        context['fav_books'] = fav_book
        return context


def like_view(request, link):
    book = get_object_or_404(Book, link=link)
    like = book.likes.filter(id=request.user.id)
    liked = False
    print(book)

    if like.exists():
        book.likes.remove(request.user)
        liked = False
    else:
        book.likes.add(request.user)
        liked = True

    return HttpResponseRedirect(reverse('read:detail', args=[link]))


class PdfView(DetailView):
    template_name = 'read/pdf_viewer.html'
    model = Book
    query_pk_and_slug = True
    slug_url_kwarg = 'link'
    slug_field = 'link'

    def get_context_data(self, *args, **kwargs):
        context = super(PdfView, self).get_context_data(*args, **kwargs)
        book = Book.objects.get(link=self.kwargs['link'])

        context['book'] = book
        return context

    @method_decorator(xframe_options_sameorigin)
    def dispatch(self, request, *args, **kwargs):
        return super(PdfView, self).dispatch(request, *args, **kwargs)


def insert_to_history(request, link):
    user_ = request.user
    get_book = get_object_or_404(Book, link=link)
    if user_.is_authenticated:
        history = HistoryRecord(user_id=request.user.id, url=str(link), book_id=get_book.id)
        history.save()
    link = str(link)
    return HttpResponseRedirect(reverse('read:book-view', args=[link]))


# class PdfView(PDFTemplateResponseMixin, DetailView):
#     template_name = 'read/pdf_viewer.html'
#     model = Book
#     context_object_name = 'book'
#     query_pk_and_slug = True
#     slug_url_kwarg = 'link'
#     slug_field = 'link'


# def url(request, path):
#     fs = FileSystemStorage()
#     filename = str(file)
#     if fs.exists(filename):
#         with fs.open(filename) as pdf:
#             response = HttpResponse(pdf, content_type='application/pdf')
#             response['Content-Disposition'] = 'attachment; filename=' + filename
#             return response
#     else:
#         return HttpResponseNotFound("sorry we couldn find the pdf that you looking for")
#     path = str(path)
#     try:
#         return FileResponse(open(path, 'rb'), content_type='application/pdf')
#     except FileNotFoundError:
#         raise
#
#
# def pdf_view(request, link):
#     book = get_object_or_404(Book, link=link)
#     context = {
#         'book': book,
#     }
#     return render(request, 'read/pdf_viewer.html', context)


def maps_view(request):
    return render(request, 'read/maps.html')

read/templates/read/add-comment.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}{{book.title}}{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/details.css' %}">
{% endblock %}

{% block content %}

    <section class="container my-5">
        <div class="card border-0 " >
            <div class="card-body ">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% load crispy_forms_tags %}
                        {{ form.media }}
                        {{form | crispy}}
                        <div class="form-group">
                            <button class="btn btn-primary"> Save </button>
                        </div>
                    </form>
            </div>
        </div>
    </section>
{% endblock %}

read/templates/read/details.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}{{book.title}}{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/details.css' %}">
<style>
.icon{
    height: 24px;
    color: mediumvioletred;
}
</style>
{% endblock %}

{% block content %}
    <div class="jumbotron bg-primary">
        <div class="d-flex justify-content-center">
            <img src="{% static 'images/profile.svg' %}" height="400" class="img-fluid jumbtrn-image" alt="">

        </div>
        <div class="container mt-5">
            <h1 class="text-center font-weight-bold">Detail Buku</h1>

        </div>
    </div>
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <div class="d-flex flex-column align-items-center justify-content-center ">
                        <img class="img-fluid img-content" src="{{ book.cover.url }}" height="500" alt="">

                        <h4 class="mt-3"> <span class="text-primary ">Di publikasi tanggal </span> : {{ book.upload_date | date:"SHORT_DATE_FORMAT" }}</h4  >
                        <div class="d-flex flex-column w-75 py-2 mb-5">
                            <a href="{{ book.book.url }}" download="{{ book.book.url }}" class="btn btn-primary mb-3">Download</a>
                            <a href="{% url 'read:book-history' book.get_absolute_url %}" class="btn btn-danger">Baca</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-5">
                    <div class="d-flex flex-row justify-content-between">
                        <div>
                            <h2 class="font-weight-bold">{{ book.title }}</h2>
                            <p class="text-primary">By : {{ book.author }}</p>
                        </div>
                        {% include 'read/like.html' %}
                    </div>
<!--                    <h2 class="font-weight-bold">{{ book.title }}</h2>-->
<!--                    <p class="text-primary">By : {{ book.author }}</p>-->
                    <hr>
                    <h3>Deskripsi Singkat</h3>
                    <div class="">{{ book.description | safe }}</div>
                    <h3>Informasi : </h3>
                    <p>Uploader : <span class="font-weight-bold">{{ book.uploader.profile.name }}.</span> <a href="https://wa.me/{{ book.uploader.profile.phone }}" class="text-info">Klik Disini Untuk Chat</a> </p>
                    <h3>Disukai : </h3>
                    <p>{{ book.ttl_like }}</p>
                </div>
            </div>

        </div>


    </div>
    <div id="comments1">

        <div class="card border-0 mb-1">
            <div class="card-body">
                <div class="container">
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'read:add-comment' book.get_absolute_url %}" class="text-info">Tambahkan komentar</a>

                    </div>
                    {% if book.comment.all %}

                        {% for comment in book.comment.all %}
                        <div>
                            <div class="font-weight-bold mt-5">{{ comment.name }}</div>
                            <div>{{ comment.body | safe }}</div>
                            <hr>
                        </div>
                        {% endfor %}

                    {% else %}
                    <div>
                        <p>Belum Ada Komentar....</p>
                        <p>Berikan Komentar dengan klik tombol Pill yang ada</p>
                    </div>
                    {% endif %}

                </div>

            </div>
        </div>
    </div>
{% endblock %}

read/templates/read/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <div class="jumbotron bg-primary">
        <div class="container d-flex flex-column align-items-center ">
           <img class="img-fluid" src="{% static 'baru/assets/images/Jumbotron.svg' %}" alt="">
            <h1 class="mt-5 mb-3">Belajar apapun disini melalui buku yang sudah tersedia diwebsite ini.</h1>
            <a class="btn btn-danger w-25 mb-3 ">List Buku</a>
        </div>
    </div>

    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <img class="img-fluid" src="{% static 'baru/assets/images/Asset 1.svg' %}" alt="">
                </div>
                <div class="col-lg-6 caption mt-5 pl-5">
                    <h3 class="pt-3">Gratis E-Books</h3>
                    <p class="text-secondary pt-3">Baca buku gratis seperti buku sekolah dari SD, SMP, SMK atau SMA, buku buku tersebut dibagikan secara gratis untuk menunjang pelajaran kamu supaya lebih giat membaca buku</p>
                    <a href="" class="btn btn-primary mt-3">Explore buku</a>
                </div>
            </div>
        </div>
    </div>

    <div id="favorite-book" class="mt-5 mb-5 bg-primary text-white pt-5 pb-5">
        <h1 class="text-center  font-weight-bold">Favorite Book</h1>
        <p class="text-center">Berikut ini adalah buku favorite yang diambil berdasarkan rating dan jumlah pembacanya </p>
        <div class="container">
            <div class="row">
            {% for book in fav_books %}
                <div class="col-sm-4 mt-5">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="{{ book.cover.url }}" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text text-dark font-weight-bold">{{ book.title }}</p>
                            <a href="{{ book.get_absolute_url }}" class="text-info">Kunjungi buku</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>

    <div id="search">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1 class="text-primary font-weight-bold">Cari buku </h1>
                    <p class="text-secondary">Cari buku apapun yang kamu suka entah itu komik atau buku pelajaran yang kamu sukai, lalu pelajari buku tersebut secara perlahan lahan sampai buku itu habis kamu baca </p>
                </div>

                <div class="col-sm-6">
                    <form action="{% url 'read:book-list' %}" method="get">
                        <div class="input-group " style="margin-top:60px">
                            <input type="text" name="q" class="form-control border-0 ">
                        <button type="submit" class="btn btn-primary">Search</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div id="pencapaian" class="bg-primary">
        <div class="container mt-5">
            <div class="d-flex flex-column align-items-center ">
            <h1 class="text-white mt-4">Pencapaian</h1>
            <p class="text-white mt-4 mb-4">Pencapaian yang kita dapat saat ini, ayo saatnya gabung bersama member lainnya dan juga bisa menambahkan pengetahuan kamu berdasarkan apa yang kamu cari.</p>

            </div>
            <div class="row pb-5">

                <div class="col-lg-4">
                    <div class="card">
                        <img src="{% static 'baru/assets/images/Book.svg' %}" alt="" class="pt-3" height="120">
                        <div class="card-body text-center">
                            <h4>Total Buku</h4>
                            <p>{{ book_total }} Buku</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="card">
                        <img src="{% static 'baru/assets/images/Member.svg' %}" alt="" class="pt-3" height="120">
                        <div class="card-body text-center pb-3">
                            <h4>Total Member</h4>
                            <p>{{ member }} Member</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="card">
                        <img src="{% static 'baru/assets/images/Kategori_1.svg' %}" alt="" class="pt-3" height="120">
                        <div class="card-body text-center">
                            <h4>Total Kategori</h4>
                            <p>{{ category }} kategori</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div id="content" class=" my-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <img class="img-fluid" src="{% static 'baru/assets/images/Asset 1.svg' %}" alt="">
                </div>
                <div class="col-lg-6 caption mt-5 pl-5">
                    <h3 class="pt-3">Bagikan Buku</h3>
                    <p class="text-secondary pt-3">Kamu bisa menjual buku kamu disini dan bisa berperan penting sebagai donatur pembagi buku sehingga bisa meningkatkan angka literasi diindonesia dengan cara itu.</p>
                    <a href="/my/" class="btn btn-primary mt-3">Upload Buku</a>
                </div>
            </div>
        </div>
    </div>
    <div class="perpustakaan-maps bg-primary text-white mt-5 pt-5 ">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-6 mt-5">
                    <h3 class="font-weight-bold">Perpustakaan terdekat</h3>
                    <p>Selain membaca buku kamu bisa menemukan perpustakaan terdekat lho, penasaran? yuk klik dibawah ini untuk menggunakan fitur perpustakaan terdekat</p>
                    <a href="" class="btn btn-danger">Lihat Peta</a>
                </div>
                <div class="col-lg-6">
                    <img src="{% static 'images/perpus.svg' %}" alt="Perpustakaan terdekat">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

read/templates/read/like.html
                        <form method="post" action="{% url 'read:book-like' book.get_absolute_url %}">
                            {% csrf_token %}
                            {% if not liked %}
                            <button class="btn">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor" class="icon">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                                </svg>
                            </button>
                            {% else %}
                             <button class="btn" href="#liked">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                                    class="icon">
                                    <path fill-rule="evenodd"
                                        d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
                                        clip-rule="evenodd" />
                                </svg>
                            </button>
                            {% endif %}
                        </form>

read/templates/read/list.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}Book List{% endblock %}

{% block style %}
<style>
    body {
        background-color: #eee;
    }
</style>
<link rel="stylesheet" href="{% static 'css/image-stabilizer.css' %}">

{% endblock %}

{% block content %}
<div class="jumbotron bg-primary">
    <div class="container">
        <div class="row">
            {% for new in new_book %}
            <div class="col-lg-6 mb-5">
                <div class="d-flex justify-content-center">
                    <img class="img-fluid " src="{{ new.cover.url }}" alt="">
                </div>
            </div>

            <div class="col-lg-6">
                <h1 class="text-white font-weight-bold">{{ new.title }}</h1>
                <p class="text-white">{{ new.description | safe }}</p>
                <a href="{% url 'read:detail' new.get_absolute_url %}" class="btn btn-danger">Detail Buku</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="container">

</div>
<div class="card">
        <div class="card-body">
            <div class="book mb-5">
    <div class="container">
        <div class="card mb-5">
            <div class="card-body">
                <form method="get" class="input-group ">
                    <input type="text" name="q" class="form-control" placeholder="Cari buku yang anda inginkan disini">
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-8">

                <div class="row">
                    {% for book in object_list %}
                    <div class="col-lg-4 mt-4">
                        <div class="card border-0">
                            <div class="book-img-container overflow-hidden">
                                <img src="{{ book.cover.url }}" alt=""
                                    class="card-img-top img-fluid book-img">
                            </div>
                            <div class="card-body">
                                <p>{{ book.title }}</p>
                                <a href="{% url 'read:detail' book.get_absolute_url %}" class="text-primary font-weight-bold">Lihat buku</a>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                </div>

                {% if is_paginated %}=
                <nav class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Next"><span aria-hidden="true">«</span></a></li>
                        {% endif %}
                        <li class="page-item active"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                        {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                        {% endif %}

                    </ul>
                </nav>
                {% endif %}

            </div>
            <div class="col-lg-4">
                <div class="card border-0">

                    <div class="card-body">
                        <h3 class="font-weight-bold ">Favorite book</h3>
                        <hr class="mt-4"> {% for fav in fav_books %}
                        <div class="d-flex">
                            <img height="150" class="mt-3" src="{{ fav.cover.url }}" alt="">
                            <div class="caption ml-3">
                                <p class="font-weight-bold">Siswa handal pelajaran madrasah</p>
                                <p>Dengan ini anda bisa melihat bagaimana sih cara belajar anak madrasah</p>
                                <a href="{% url 'read:detail' fav.get_absolute_url %}" class="text-primary">Lihat buku</a>
                            </div>
                        </div>
                        <hr> {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
        </div>
    </div>
</div>



{% endblock %}

read/templates/read/maps.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}Peta | Home
{% endblock %}

{% block style %}

    <style>
        #map {
            width: 100%;
            height: 400px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="jumbotron bg-primary">
        <div class="container">
            <div class="d-flex justify-content-center">
                <img height="400" src="{% static 'images/maps.svg' %}" alt="">

            </div>
            <h1 class="text-center font-weight-bold text-white pt-5">Peta Perpustakaan</h1>
            <p class="text-center text-white">Temukan perpustakaan yang kamu inginkan disini untuk berdiskusi ataupun <br> belajar bersama dengan teman teman sekelilingmu</p>

        </div>
    </div>
    <section id="maps" class="mt-5 mb-5">
        <div id="map"></div>
        <div class="d-flex justify-content-center">
            <a href="/" class="btn btn-primary mt-3">Kembali ke home</a>
        </div>
    </section>
{% endblock %}


{% block js %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
    <script src="{% static 'js/maps.js' %}"></script>
{% endblock %}

read/templates/read/pdf_viewer.html
{% extends 'base.html' %}

{% load static %}
{% load l10n %}
{% load i18n %}

{% block title %}{{ book.title }}{% endblock %}

{% block content %}
    <div class="embed-responsive embed-responsive-16by9">
        <iframe src="{{ book.book.url }}" type="application/pdf" class="embed-responsive-item"></iframe>
    </div>
{% endblock %}